version: '3.8'
services:
  traefik:
    image: traefik:v2.4
    networks:
      - example_network
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - target: 80
        published: 80
        mode: host
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
      # Monitor http://127.0.0.1:8080/
      - target: 8080
        published: 8080
        mode: host
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/traefik.yml:/traefik.yml:ro
      - ./docker/traefik/traefik-certs.yml:/traefik-certs.yml
      - ./docker/traefik/certificates/:/certificates

  web:
    build:
      context: .
      dockerfile: "docker/web/Dockerfile"
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    networks:
      - example_network
    labels:
      - "traefik.enable=true"
      - "traefik.backend=web"
      - "traefik.http.routers.web.rule=Host(`example.test`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.services.web.loadbalancer.server.scheme=http"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  example_network: