### Providers
providers:
  docker:
    network: example_network
    exposedByDefault: false
  file:
    filename: /traefik-certs.yml
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

accessLog: {}
log:
  level: ERROR

api:
  dashboard: true
  insecure: true